### ISSUE TITLE
ioncube_loader is hard coded to php 5.3

### ISSUE THREAD

**Issue by nicolas74** [werdan/php-ioncube#2]
/cookbooks/php-ioncube/recipes/default.rb

zend_extension=/usr/local/ioncube/ioncube_loader_lin_5.3.so

**Comment by werdan** [comment]
Hello, that's true.
Even more, it is hardcoded to 64bit.
I'll welcome all pull requests on this subject.

Andriy

**Comment by nicolas74** [comment]
As I'm a newbe on github I forked your project and add a small modification to allow user to change version from node attribute.

Thanks for your comprehension.

**Comment by werdan** [comment]
Hello Nicolas! (Bonjour?)

Please, make a Pull request (https://help.github.com/articles/using-pull-requests) so that I can merge it to make repo

Andriy

**Comment by werdan** [comment]
Hello,

Thanks to @JasonBoyles efforts you can now specify php version in attributes.
Also, php version is determined during installation automatically, unless you provide it in attributes.

Andriy
