### ISSUE TITLE
ioncube.ini file resource notifications: what if you're not running apache?

### ISSUE THREAD

**Issue by JasonBoyles** [werdan/php-ioncube#6]
There's a "notifies:" line in the default recipe:

https://github.com/werdan/php-ioncube/blob/b663cb2a5fdcdc38564195603dc4c082517dc155/recipes/default.rb#L56

This notifies the apache2 service when the ioncube.ini file is updated.

Not everyone is running apache2... they might be running nginx with php-fpm, or something else.

One solution to this is to make the ionCube installation function an LWRP which takes a list of things to notify as input.

**Comment by JasonBoyles** [comment]
I suppose the proper way to do this, without writing an LWRP, is to subscribe to the ioncube.ini template like so:

``` ruby
service "apache" do
  supports :restart => true, :reload => true
  action :enable
  subscribes :reload, "template[#{node['php']['ext_conf_dir']}/ioncube.ini]", :delayed
end
```

Although that seems like a burden on the user.

**Comment by werdan** [comment]
Another option is to remove notifies at all and let use notify services as needed.

This cookbook is actually a replacement for "package 'php-ioncube'" which should not depends on any webservers at all.

What do you think?

**Comment by JasonBoyles** [comment]
I agree with removing the hard-coded notification. Ultimately I think it should be a simple LWRP so we can tell chef if we changed anything, and it can notify the resources the user told it to.

**Comment by JasonBoyles** [comment]
pull request sent: https://github.com/werdan/php-ioncube/pull/8

**Comment by JasonBoyles** [comment]
The only way we can use Chef resources within an LWRP and still notify top-level resources in the event of changes is to use the Chef-11-only 'use_inline_resources' line:

http://docs.opscode.com/lwrp_custom_provider.html#use-inline-resources

This will be the default for chef-client at some point, but including it here will make this recipe Chef 11-only.

Not sure if this can be conditionally set.

If we leave it as a recipe, the only way users can conditionally notify their own resources would be to subcribe to the file resource called #{node[:php][:ext_conf_dir]}/ioncube.ini, which is really ugly.

**Comment by werdan** [comment]
What is the problem to use chef standard way of LWRP usage like:

ioncube do
 action "install"
 notifies :restarte,"service['apache2']"
end

Of course, we'll need to rewrite recipe to LWRP in this case...

**Comment by JasonBoyles** [comment]
I have a first pass at an LWRP for this, hoping to send you a pull request sometime today so you can check it out.

The problem is, if you use the Chef DSL and define resources within a provider, they cannot notify higher-level resources (ones invoked in the parent recipe). In the case you describe, apache2 would never be notified because it's already been processed by the time the resources in the LWRP are being processed.

Chef 11 introduces the "use_inline_resources" key word which will cause the resourced invoked in the LWRP to run as top-level resources, which can notify normally. I've confirmed this works fine in Chef 11.

**Comment by werdan** [comment]
Hello Jason,

All your pull requests that converts cookbook to LWRP usage are accepted. 
This issue can be closed now

Thank you very much for your help!

Andriy
